### ISSUE TITLE
Second hint looks confusing to me

### ISSUE THREAD

**Issue by ghost** [CheckiO-Missions/checkio-mission-friends#10]
Hi!

```
Create two sets (arrays) for future and visited nodes. Start at the first node (second argument), add it to visited. Find all of the neighbors and add them to the "future" set.
```

I can't understand this part, should I do the following:
    visited = {first}
    future = {f for f in network if first not in f.split('-')}
?

**Comment by oduvan** [comment]
closed, as hints are removed for that mission
